### ISSUE TITLE
Got "undefined is not an object.." error

### ISSUE THREAD

**Issue by stanlogin** [callstack-io/react-native-fbads#16]
react native 0.36
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import { NativeAdsManager } from 'react-native-fbads';
const adsManager = new NativeAdsManager(MY_PLACE_ID, 1);
...
`
<img width="320" alt="screen shot 2016-10-30 at 4 30 53 am" src="https://cloud.githubusercontent.com/assets/376822/19832603/2603e7f4-9e5a-11e6-9f16-e78081a4049d.png">
Followed all the steps.

**Comment by grabbou** [comment]
Hey, have you linked native modules correctly and rerun the app? Looks like it's missing and causing the above error .

**Comment by stanlogin** [comment]
It already works, and yes it is linking problem. Thank you for your reply.
