### ISSUE TITLE
Native ads on android is not clickable

### ISSUE THREAD

**Issue by huynhloc** [callstack-io/react-native-fbads#17]
I have run example on android, native ads has shown but when I touch it have no reaction.

**Comment by stanlogin** [comment]
Same here. ios works. android ads showing but not clickable.

**Comment by stanlogin** [comment]
@grabbou , have you tested ad in Android and it works? I want to know is it a installation problem in my side. Thank you.

**Comment by macuna** [comment]
I have the same problem, the native banner isn't clickable on Android

Did you find the problem @grabbou ?

Thanks

**Comment by eranbes** [comment]
Common guys. Lets make Native Ads great again :-)

**Comment by macuna** [comment]
Any news here ?

**Comment by eranbes** [comment]
Had a chat with @grabbou. He said they are looking into that.

**Comment by danny-chen** [comment]
it works for me to handle onInterceptTouchEvent() and onTouchEvent() in NativeAdView.java
   
sample code:

    private int CLICK_ACTION_THRESHHOLD = 200;
    private float startX;
    private float startY;

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return true;
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        switch (ev.getActionMasked()) {
            case MotionEvent.ACTION_DOWN:
                startX = ev.getX();
                startY = ev.getY();
                break;
            case MotionEvent.ACTION_UP:
                float endX = ev.getX();
                float endY = ev.getY();
                if (isAClick(startX, endX, startY, endY)) {
                    performClick();
                }
                break;
        }
        return true;
    }

    private boolean isAClick(float startX, float endX, float startY, float endY) {
        float differenceX = Math.abs(startX - endX);
        float differenceY = Math.abs(startY - endY);
        if (differenceX > CLICK_ACTION_THRESHHOLD/* =5 */ || differenceY > CLICK_ACTION_THRESHHOLD) {
            return false;
        }
        return true;
    }

**Comment by grabbou** [comment]
This is now fixed, thanks for suggested solutions. We will work on a better workaround later.

**Comment by eranbes** [comment]
I still cannot get it to work.  
I see the changes in the code but there is no click event. Where is performClick() defined?

**Comment by Yukaii** [comment]
I notice that in https://github.com/callstack-io/react-native-fbads/issues/17#issuecomment-265990892 @danny-chen wrote:

```java
@Override
public boolean onInterceptTouchEvent(MotionEvent ev) {
    return true;
}

// ... other code
```

but #21 missed it.

I got native ad click working until I add back these lines manually.

**Comment by satya164** [comment]
Can you send a PR for that?

**Comment by Yukaii** [comment]
@satya164 see #26 😄

**Comment by SkyTreasure** [comment]
Hi this seems like old thread, but i am using "react-native-fbads": "^6.1.0" and still facing this issue.  Am i missing something?

**Comment by Suraj-Tiwari** [comment]
Are you sure you are using TriggerableView.
in no, please share your implementation.

**Comment by SkyTreasure** [comment]
```
import React, { Component } from "react";
import { Text, View, Dimensions } from "react-native";
import {
  withNativeAd,
  AdIconView,
  TriggerableView,
  MediaView,
  AdChoicesView
} from "react-native-fbads";

import { colors } from "../styles/index.style";
const { width } = Dimensions.get("window");

class SmallNativeAd extends React.Component {
  render() {
    return (
      <View
        style={{
          backgroundColor: this.props.color,
          flexDirection: "column",
          borderRadius: 10,
          marginStart: 5,
          marginEnd: 10,
          marginTop: 10
        }}
      >
        <AdChoicesView style={{ position: "absolute", right: 0, top: 0 }} />

        <View style={{ flexDirection: "row" }}>
          <AdIconView style={{ marginStart: 10, width: 40, height: 40 }} />
          <View
            style={{ flexDirection: "column", paddingHorizontal: 10, flex: 1 }}
          >
            <TriggerableView style={{ fontSize: 14, color: "white" }}>
              {this.props.nativeAd.headline}
            </TriggerableView>
            <Text style={{ color: "gray", fontSize: 12 }}>
              {this.props.nativeAd.sponsoredTranslation}
            </Text>
          </View>
        </View>
        <View style={{ alignItems: "center", marginStart: 10, marginEnd: 10 }}>
          <TriggerableView style={{ fontSize: 10, color: "white" }}>
            {this.props.nativeAd.linkDescription}
          </TriggerableView>
          <TriggerableView
            style={{
              fontSize: 15,
              color: "white",
              marginTop: 5,
              paddingVertical: 5,
              paddingHorizontal: 30,
              height: 30,
              borderTopWidth: 0,
              backgroundColor: "#01b45e",
              elevation: 3,
              marginBottom: 10,
              borderColor: "white",
              borderRadius: 6
            }}
          >
            {this.props.nativeAd.callToActionText}
          </TriggerableView>
        </View>
      </View>
    );
  }
}

export default withNativeAd(SmallNativeAd);
```
And I getting 0 impressions for ads which are not clickable.

**Comment by AndresPrez** [comment]
Hello @Suraj-Tiwari, **TriggerableView** not clickable on android with react native >0.6
I have a similar implementation than @SkyTreasure
I'm using "react-native-fbads": "^6.3.1"

**Comment by tmjordan** [comment]
@Suraj-Tiwari even normal bannerview are not clickable
