### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeFbads.InterstitialAdManager.showAd')

### ISSUE THREAD

**Issue by macuna** [callstack-io/react-native-fbads#18]
Hi, I just made a simple test in order to see how the interstitial works but I got this error.

<img width="280" alt="screen shot 2016-11-23 at 4 36 12 pm" src="https://cloud.githubusercontent.com/assets/63238/20576079/fc074e56-b19a-11e6-92c6-8c80e783338d.png">

I ran this 

react-native install react-native-fbads

and my code is this

import { InterstitialAdManager } from 'react-native-fbads'
InterstitialAdManager.showAd("my_ad_code")
.then(didClick => {console.log("click")})
.catch(error => {console.log("error")})

Any advice ?

Thanks

**Comment by stanlogin** [comment]
In my own experience, "react-native install react-native-fbads" is not enough, I have to manually link the module for both ios and android.

**Comment by macuna** [comment]
I don't quite sure about how to manually linking the module and I don't see anything in the docs of this project. 

Can someone tell me how?

Thanks

**Comment by satya164** [comment]
`react-native link react-native-fbads`

**Comment by macuna** [comment]
Thanks!
