### ISSUE TITLE
Unable to show Ads

### ISSUE THREAD

**Issue by klyment** [callstack-io/react-native-fbads#20]
I tried to display native ads and interstitial ads, both of them got the similar error: 
undefined is not an object ( evaluating CTKNativeAdManager.init)
undefined is not an object ( evaluating _reactNativeFbads.InterstitialAdManager.showAd)

**Comment by grabbou** [comment]
Please remember to run `react-native link` - you are missing the native modules.

**Comment by dannyyaou** [comment]
@grabbou Thanks for the module first, but actually rnpm really doesn't link in android version
