### ISSUE TITLE
Android was not automatically link

### ISSUE THREAD

**Issue by hoangdoan267** [callstack-io/react-native-fbads#29]
I use `react-native link` for our library but it just automatically linked to my ios project, on Android version, I had to manually link.
But it throw an error:  "io.callstack.react.fbads.FBAdsPackage" does not exist.

**Comment by grabbou** [comment]
Does it link other projects to your Android? Please double check as it's likely an error on your side. Happy to provide you some tips.

I assume that after manual linking everything went well, right?

**Comment by hoangdoan267** [comment]
I think the problem was about your newest update, my colleague had the same issue, too. Linking manually made everything ok but that's a waste of time.

**Comment by hoangdoan267** [comment]
@grabbou I think manually linked like your example is not working
