### ISSUE TITLE
dist/lib/index.js is missing according to package.json file

### ISSUE THREAD

**Issue by MuhammadRafeh** [callstack-io/react-native-fbads#339]
`dist/lib/index.js` is missing according to package.json file

**Comment by murtaza-ahmad-khan** [comment]
error: Error: While trying to resolve module `react-native-fbads`.
package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved.

**Comment by MuhammadRafeh** [comment]
@murtaza-ahmad-khan go to package.json file of nodemodules/react native fbads and then package. Json and change the main value to the src/index.ts

**Comment by murtaza-ahmad-khan** [comment]
> src/index. Js or index.ts

@MuhammadRafeh Thank you so much yar ❤️

**Comment by MuhammadRafeh** [comment]
@murtaza-ahmad-khan no problem jigar ❤️
