### ISSUE TITLE
Error on adViewDidClick when clicking on Banner Ad

### ISSUE THREAD

**Issue by 7kfpun** [callstack-io/react-native-fbads#35]
```
<BannerView
    type="standard"
    placementId="*****************"
    onClick={() => console.log('click')}
    onError={(err) => console.log('error', err)}
/>
```
<img width="848" alt="screen shot 2017-02-07 at 10 17 52 pm" src="https://cloud.githubusercontent.com/assets/2672802/22694787/799731d2-ed83-11e6-8781-a7d304abd838.png">

**Comment by JUnderwood1991** [comment]
Having this issue too, I'm guessing the Author doesn't care

**Comment by Tiendq** [comment]
@JUnderwood1991 is there any issue if you remove onClick handler?

**Comment by grabbou** [comment]
You should define `onPress` instead of `onClick`. The error is because there's no handler defined for the event.

**Comment by Tiendq** [comment]
@7kfpun Banners shown on your app? I tried but always see blank banner, no ad content :(

**Comment by Tiendq** [comment]
I used this banner:

```
<BannerView
          type="standard"
          placementId="test id"
          onPress={() => console.log('click')}
          onError={(err) => console.log('error', err)}
        />
```

Add keep seeing this error in the console log, but don't know what it mean (I set 30 seconds refresh rate for the banner):

<img width="647" alt="screen shot 2017-05-23 at 3 13 31 pm" src="https://cloud.githubusercontent.com/assets/815910/26344639/948fa53e-3fca-11e7-92ed-cc253ee7c1cb.png">

**Comment by 7kfpun** [comment]
Have you updated the SDK?

**Comment by Tiendq** [comment]
@7kfpun I just install everything today, first time for this app.
