### ISSUE TITLE
Exception 'Only one `showAd` can be called at once' was throw

### ISSUE THREAD

**Issue by 7kfpun** [callstack-io/react-native-fbads#36]
Could not catch the error while calling twice.
```
InterstitialAdManager.showAd('1220388591362840_1221348381266861')
      .then(didClick => console.log('click'))
      .catch(error => console.log(error));
```

![simulator screen shot 7 feb 2017 10 23 45 pm](https://cloud.githubusercontent.com/assets/2672802/22695002/32a8e210-ed84-11e6-934e-9b91ea88f149.png)

**Comment by grabbou** [comment]
Interesting, thanks for reporting, will look into it today

**Comment by jakubsta** [comment]
@7kfpun @grabbou I've checked and indeed this could happen when you click button really fast. I've just created PR which resolve this issue.
