### ISSUE TITLE
Android install fails

### ISSUE THREAD

**Issue by commit-master** [callstack-io/react-native-fbads#38]
Hey, 

I've followed your install steps AND fbsdk's one for Android (I have no issue with iOS). But each time I try to run it (either on device or emulator), I get the following error:

```
undefined is not an object (evaluating 'CTKNativeAdManager.init')
```

Do you guys have any idea why and how I can fix this ?
Thanks !

**Comment by sfratini** [comment]
#37 Seems to be the same issue and I posted the solution there.

**Comment by grabbou** [comment]
Yup, it's a duplicate. I will investigate these issues shortly.
