### ISSUE TITLE
module FBAudienceNetwork not found

### ISSUE THREAD

**Issue by JUnderwood1991** [callstack-io/react-native-fbads#46]
Entirely frustrating issue. The project is linked. The frameworks are in the frameworks folder. Framework search path is updated to reflect the location of the frameworks, yet rn-fbads "CTKInterstitialAdManager.m' fails to build due to FBAudienceNetwork not found.

![screen shot 2017-03-03 at 9 26 15 pm](https://cloud.githubusercontent.com/assets/8592655/23575247/279f7d16-0058-11e7-9b43-fb4ab8f70e27.png)
![screen shot 2017-03-03 at 9 26 48 pm](https://cloud.githubusercontent.com/assets/8592655/23575249/2bfc11f8-0058-11e7-9dd3-dbb901c7aead.png)

**Comment by JUnderwood1991** [comment]
The iOS folder also has all the frameworks in it.

**Comment by JUnderwood1991** [comment]
Closing. rn-fbads really does want it to be ~/Documents/FacebookSDK...

**Comment by parkerproject** [comment]
What does your fix mean? cos I 'm having the same issue

**Comment by parkerproject** [comment]
I'm also pointing to ~/Documents/FacebookSDK but still not working

**Comment by qdd1** [comment]
@JUnderwood1991  How did you get it works? I moved/unzip all frameworks to "~/Documents/FacebookSDKs-iOS-4" ( event FBAudienceNetwork.framework ) but still getting the error.

**Comment by efstathiosntonas** [comment]
@qdd1 Make sure that when moving Framework files that `choose Create groups for any added folders and deselect Copy items if needed. `. Also be 100% sure that the folder name is inside your `Documents/FacebookSDK` directory and not `Downloads`. 

notice that the folder name is `FacebookSDK` and not `FacebookSDSs-iOS-4`.

**Comment by HasnainAD** [comment]
@efstathiosntonas I have everything in place as you have mentioned but I am still getting this error.
Framework Search Path is 
$(SRCROOT)/../node_modules/react-native-webrtc/ios ~/Documents/FacebookSDK $(PROJECT_DIR)

**Comment by Suraj-Tiwari** [comment]
Using pod?
if not Use pod to add fb audience sdk

**Comment by HasnainAD** [comment]
@Suraj-Tiwari Wouldn't it have any conflict with existing project resources, as none is added with pod?

**Comment by Suraj-Tiwari** [comment]
No it won't.
Just make sure to open workspace file generated by pod

**Comment by huzaima1298** [comment]
> No it won't. Just make sure to open workspace file generated by pod

hey plz there is compatabilty version error in react-native fbads. with react native 0.62 its not working
