### ISSUE TITLE
This method must be called on the main thread was thrown while invoking showAd

### ISSUE THREAD

**Issue by JUnderwood1991** [callstack-io/react-native-fbads#47]
Trying to load an interstitial ad, on touchable opacity press. Displays the error shown in the issue title. 

Exception 'This method must be called on the main thread' was thrown while invoking showAd on target CTKInterstitialAdManager with params ( "PLACEMENTID", 30, 31 )

```
              onPress = {
                () => {
                  this.showFullScreenAd()
                }
              }
```

```
  showFullScreenAd() {
    InterstitialAdManager.showAd("PLACEMENT_ID_WAS_HERE").then(didClick => {}).catch(error => {});
  }
```

**Comment by macuna** [comment]
I have the same problem, any idea?

**Comment by JUnderwood1991** [comment]
Nope.

Let's hope the author takes the time to fix his issue.

On Tue, Mar 7, 2017 at 9:39 AM, Martín Acuña Lledó <notifications@github.com

**Comment by 7kfpun** [comment]
Happen on Facebook SDK 4.20.0
(for quick fix, use the old 4.19.0 version)

**Comment by VinAppFun** [comment]
I try use the old 4.19.0 version but same error?

**Comment by satya164** [comment]
Does this happen every time? This should be easy to fix.

**Comment by 7kfpun** [comment]
Yes happen every time

**Comment by satya164** [comment]
okay, I'll try to fix it tonight.

**Comment by VinAppFun** [comment]
How to fix _onAdError event?

**Comment by grabbou** [comment]
Any luck @satya164 ?

**Comment by 7kfpun** [comment]
Update Facebook SDK to the latest version(4.22.1) will fix the problem.

**Comment by grabbou** [comment]
We bumped the Facebook SDK version for next version, so going to close it.
