### ISSUE TITLE
how to contribute document is missing

### ISSUE THREAD

**Issue by AshokICreate** [callstack-io/react-native-fbads#51]
I would like to contribute to this project please add basic guidelines.

**Comment by grabbou** [comment]
You can contribute by adding guidelines! But seriously speaking, all you have to do is to clone repo, install dependencies (npm / yarn) and run one of the scripts from [`example/package.json`](https://github.com/callstack-io/react-native-fbads/blob/master/example/package.json). Most likely start followed by `run-ios`.

Can't wait for your contributions!
