### ISSUE TITLE
justify content is not working

### ISSUE THREAD

**Issue by nimamyscreen** [callstack-io/react-native-fbads#52]
render() {
        return (
            <BannerView style={{backgroundColor:'red' , flex:1,justifyContent:'center' , marginTop:20}}
                placementId="566718123532432_613986802138897"
                type="standard"
                onClick={() => console.log('click')}
                onError={(err) => console.log('error', err)}
            />
        );
    }

![img_0062](https://cloud.githubusercontent.com/assets/16332824/24329127/3ee51a24-122f-11e7-838a-ffb20fdf0442.jpg)

**Comment by satya164** [comment]
Wrap it in a view.
