### ISSUE TITLE
CTKAdSettingsManager.currentDeviceHash undefined is not an object

### ISSUE THREAD

**Issue by namestise** [callstack-io/react-native-fbads#53]
Launching app and getting crash

I don't setup AdSetting, just render: 

```js
import { BannerView } from 'react-native-fbads';

function ViewWithBanner(props) {
  return (
    <View>
      <BannerView
        placementId="YOUR_BANNER_PLACEMENT_ID"
        type="standard"
        onClick={() => console.log('click')}
        onError={(err) => console.log('error', err)}
      />
    </View>
  );
}
```
![simulator screen shot apr 10 2017 5 53 02 am](https://cloud.githubusercontent.com/assets/20994365/24841642/f6efe6ec-1db2-11e7-9712-a01d660cdcd0.png)

**Comment by nmartin867** [comment]
I'm running into the same issue. Everything is working as expected on iOS but Android errors out immediately with the above error. Is this a configuration issue?

**Comment by satya164** [comment]
Please make sure the library is linked.

**Comment by nmartin867** [comment]
This is the same issue reported here: #37 

The solution is posted there.
