### ISSUE TITLE
Does it support rewarded audience network video ads?

### ISSUE THREAD

**Issue by rohitgoyal** [callstack-io/react-native-fbads#55]
Hi 
Does this library gives the support to integrate video ads specially rewarded ads? If not any idea if there is way to do so in a react-native app?

Thanks in advance.

**Comment by booboothefool** [comment]
@rohitgoyal I don't think so. If you look at the Facebook Audience Network dashboard, it doesn't show an option for rewarded video, only: native, interstitial, banner. 

I've successfully gotten rewarded videos working with: https://github.com/sbugert/react-native-admob

But better yet, you may want to check out http://appodeal.com mediation for all ad types and 30+ ad networks.

**Comment by rohitgoyal** [comment]
@booboothefool I got rewarded video ads via video as well. Was wondering if it was possible for Audience Network too.

**Comment by grabbou** [comment]
We support features that are available in the native sdk. Having my experience with Facebook SDK, I don't recap mention of `rewarded video`. 

As others suggested, if that's what you are looking for, then `admob` is the way to go.
