### ISSUE TITLE
[SOLVED] Duplicate zip entry - play-services-ads dependency outdated

### ISSUE THREAD

**Issue by sfratini** [callstack-io/react-native-fbads#58]
Hey

So by build is not building and the error I am getting is this:

Warning: Exception while processing task java.io.IOException: Can't write [XXXXXXXXXX/android/app/build/intermediates/transforms/proguard/debug/jars/3/1f/main.jar] (Can't read [XXXXXXXXXXXXXXX/android/app/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads/8.4.0/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:com/google/android/gms/internal/zzah.class]))
:app:transformClassesAndResourcesWithProguardForDebug FAILED

I read on the Internet that it could be due to some other modules or dependencies in other projects using a different version, which was true, since I am also using react-native-maps which was using 8.4.0 version but recently that had to be updated. 

I searched everywhere for this play-services-ads group dependency but I couldn't find it, until I did in the andorid.iml file as an exported module (I guess added by the Android API 23, not sure here)

    <orderEntry type="library" exported="" name="play-services-ads-8.4.0" level="project" />

I couldn't find this in either gradle files and I even tried to sync gradle/iml files but I couldn't. 

I fixed it in app.gradle changing this:

```grrovy
    compile project(':react-native-fbsdk')
```

to this:

```groovy
    compile (project(':react-native-fbsdk')) {
        exclude group: 'com.google.android.gms', module: 'play-services-ads'
    }
    compile "com.google.android.gms:play-services-ads:10.2.0"
```

**Comment by satya164** [comment]
your fix is correct.
