### ISSUE TITLE
CTKAdSettingsManager.currentDeviceHash error

### ISSUE THREAD

**Issue by vu-dang** [callstack-io/react-native-fbads#64]
I'm getting this error on Android at startup: undefined is not an object (evaluating 'CTKAdSettingsManager.currentDeviceHash')

**Comment by asgvard** [comment]
@vu-dang Add this into your /android/app/build.gradle:

dependencies {
    compile project(':react-native-fbads')
    .....
    compile 'com.facebook.android:audience-network-sdk:4.+'     <----- THIS
}

Facebook updated their SDK, and now forces everyone to use new version. And this package is depended on the old 4.22.1 one. You need to override this dependency.

**Comment by wojteg1337** [comment]
Did you link properly ? @vu-dang

**Comment by vu-dang** [comment]
Yes, I got it to work using the instruction from Admob mediation.
