### ISSUE TITLE
Error CTKAdSettingManager.currentDeviceHash

### ISSUE THREAD

**Issue by QuangTranSoict** [callstack-io/react-native-fbads#70]
![simulator screen shot jul 24 2017 10 22 29 pm](https://user-images.githubusercontent.com/19943271/28530607-9cbd07b8-70be-11e7-8e0c-b5453264ea7d.png)

**undefined is not an object (evaluating CTKAdSettingManager.currentDeviceHash').**
Help me. I can't run project on my device or my simulator.
In newest version.

**Comment by kyo504** [comment]
@QuangTranSoict Could you check your fbsdk version? I had a sample problem and fixed after changing version to latest version(v4.24.0)

**Comment by QuangTranSoict** [comment]
i have installed fbsdk version is v4.24.0 via cocoa-pod. But no happened.

**Comment by satya164** [comment]
Have you linked the library with `react-native link`?

**Comment by QuangTranSoict** [comment]
Yes.. i did

Vào Th 3, 25 thg 7, 2017 lúc 17:55 Satyajit Sahoo <notifications@github.com>
đã viết:

**Comment by grabbou** [comment]
You need to double check if the native module is properly linked. The error message says that there's no native module.
