### ISSUE TITLE
Any plans for implementing Rewarded Videos?

### ISSUE THREAD

**Issue by lgn-lvx3** [callstack-io/react-native-fbads#95]
Looks to be included in the 'latest' sdk, I was wondering if you guys are already working on this before I start to implement my own. Ideally I would build on this project and add a pull request, but I don't have a lot of module dev experience.

https://developers.facebook.com/docs/audience-network/ios/rewarded-video

**Comment by Trancever** [comment]
Hi @hzyIO . We are not planning to implement this feature by ourselves, but we are happy with contributions from community. Feel free to submit a PR.

**Comment by Trancever** [comment]
@hzyIO Thanks for implementing that!

**Comment by hzyIO** [comment]
No problem @Trancever , thank you guys for all of your awesome work.
